export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const SIGNOUT = 'SIGNOUT';

export const GETNEWPOSTS_REQUEST = 'GETNEWPOSTS_REQUEST';
export const GETNEWPOSTS_SUCCESS = 'GETNEWPOSTS_SUCCESS';
export const GETNEWPOSTS_FAILURE = 'GETNEWPOSTS_FAILURE';
